env=SDL_VIDEODRIVER,wayland
env=CLUTTER_BACKEND,wayland
env=QT_QPA_PLATFORMTHEME,qt6ct
env=QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env=ELECTRON_OZONE_PLATFORM_HINT,auto

# NVIDIA
env=NVD_BACKEND,direct
env=LIBVA_DRIVER_NAME,nvidia
env=__GLX_VENDOR_LIBRARY_NAME,nvidia
env=__GL_GSYNC_ALLOWED,1
env=__GL_VRR_ALLOWED,1
env=__GL_MaxFramesAllowed,1
env=PROTON_ENABLE_NGX_UPDATER,1
