[ids]
*

[main]
# При зажатии Caps Lock активируется слой "nav"
# При одиночном быстром нажатии Caps сработает как Escape (бонус для Vim!)
capslock = overload(nav, esc)

[nav]
# Стрелочки на H, J, K, L
h = left
j = down
k = up
l = right

# Дополнительно: Home/End прямо под пальцы!
a = home
e = end

# PageUp / PageDown
u = pageup
d = pagedown
