# Application bindings
bind = $mainMod, RETURN, exec, $terminal
bindd = $mainMod, E, File manager, exec, uwsm-app -- $fileManager --new-window
bind = $mainMod, B, exec, $browser
bind = $mainMod SHIFT, T, exec, $terminal -e btop
bindd = $mainMod, D, Docker, exec, $terminal -e lazydocker
bind = $mainMod, GRAVE, exec, flatpak run org.telegram.desktop
bind = $mainMod, Q, exec, throne
bind = $mainMod, L, exec, localsend

# Menus
bindd = $mainMod, SPACE, Launch apps, exec, $appsMenu
bindd = $mainMod ALT, SPACE, Omarchy menu, exec, omarchy-menu
bindd = $mainMod, ESCAPE, System menu, exec, omarchy-menu system

# Control panels
bindd = $mainMod SHIFT, A, Audio controls, exec, $terminal -e wiremix 
bindd = $mainMod SHIFT, B, Bluetooth controls, exec, $terminal -e bluetui
bindd = $mainMod SHIFT, W, Wifi controls, exec, $terminal -e impala



