# Close windows
bindd = $mainMod, W, Close window, killactive,
bindd = CTRL ALT, DELETE, Close all windows, exec, omarchy-hyprland-window-close-all

# Copy / Paste
bindd = $mainMod, C, Universal copy, sendshortcut, CTRL, Insert,
bindd = $mainMod, V, Universal paste, sendshortcut, SHIFT, Insert,
bindd = $mainMod, X, Universal cut, sendshortcut, CTRL, X,
bindd = $mainMod CTRL, V, Clipboard manager, exec, omarchy-launch-walker -m clipboard

# Lock system
bindd = $mainMod SHIFT, L, Lock system, exec, omarchy-lock-screen

# Switch workspaces with $mainMod + [0-9]
bindd = $mainMod, code:10, Switch to workspace 1, workspace, 1
bindd = $mainMod, code:11, Switch to workspace 2, workspace, 2
bindd = $mainMod, code:12, Switch to workspace 3, workspace, 3
bindd = $mainMod, code:13, Switch to workspace 4, workspace, 4
bindd = $mainMod, code:14, Switch to workspace 5, workspace, 5
bindd = $mainMod, code:15, Switch to workspace 6, workspace, 6
bindd = $mainMod, code:16, Switch to workspace 7, workspace, 7
bindd = $mainMod, code:17, Switch to workspace 8, workspace, 8
bindd = $mainMod, code:18, Switch to workspace 9, workspace, 9
bindd = $mainMod, code:19, Switch to workspace 10, workspace, 10

# Move active window to a workspace with $mainMod + SHIFT + [0-9]
bindd = $mainMod SHIFT, code:10, Move window to workspace 1, movetoworkspace, 1
bindd = $mainMod SHIFT, code:11, Move window to workspace 2, movetoworkspace, 2
bindd = $mainMod SHIFT, code:12, Move window to workspace 3, movetoworkspace, 3
bindd = $mainMod SHIFT, code:13, Move window to workspace 4, movetoworkspace, 4
bindd = $mainMod SHIFT, code:14, Move window to workspace 5, movetoworkspace, 5
bindd = $mainMod SHIFT, code:15, Move window to workspace 6, movetoworkspace, 6
bindd = $mainMod SHIFT, code:16, Move window to workspace 7, movetoworkspace, 7
bindd = $mainMod SHIFT, code:17, Move window to workspace 8, movetoworkspace, 8
bindd = $mainMod SHIFT, code:18, Move window to workspace 9, movetoworkspace, 9
bindd = $mainMod SHIFT, code:19, Move window to workspace 10, movetoworkspace, 10

# TAB between workspaces
bindd = $mainMod, TAB, Next workspace, workspace, e+1
bindd = $mainMod SHIFT, TAB, Previous workspace, workspace, e-1


