# Cursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Платформы (стандартные для Wayland)
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

# NVIDIA специфичные (аппаратное ускорение + плавность)
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_GSYNC_ALLOWED,1
env = __GL_VRR_ALLOWED,1  # Поставь 0, если игры глючат

# Браузеры, Electron (Steam, Discord, VS Code)
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# Для Proton/Steam (NGX для DLSS/FSR, низкий input lag)
env = __GL_MaxFramesAllowed,1
env = PROTON_ENABLE_NGX_UPDATER,1

# Фикс курсора (NVIDIA)
cursor {
    no_hardware_cursors = true
}

xwayland {
    force_zero_scaling = false
}

