# Base
source = ~/.config/mango/conf/autostart.conf
source = ~/.config/mango/conf/env.conf
source = ~/.config/mango/conf/base_input.conf
source = ~/.config/mango/conf/visual.conf

# Bindings
source = ~/.config/mango/bindings/apps.conf
source = ~/.config/mango/bindings/media.conf
source = ~/.config/mango/bindings/system.conf

# Optionals
source = ~/.config/mango/hardware.conf
source = ~/.config/mango/monitors.conf
source = ~/.config/mango/input.conf
