# Cursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Платформы (стандартные для Wayland)
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

# AMD специфичные (Mesa / RADV)
env = LIBVA_DRIVER_NAME,radeonsi
env = VDPAU_DRIVER,radeonsi
# Форсируем использование открытого драйвера RADV (обычно лучше для игр)
env = AMD_VULKAN_ICD,RADV 

# Переменные для производительности в играх
env = MESA_VK_WSI_PRESENT_MODE,mailbox # Снижает задержку ввода (аналог Fast Sync)

# Браузеры и Electron (Steam, Discord, VS Code)
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto

xwayland {
    force_zero_scaling = true
}