general {
    lock_cmd = hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = mmsg dispatch sleep_monitor, eDP-1
    inhibit_sleep = 3
}

listener {
    timeout = 1790
    on-timeout = loginctl lock-session
}

listener {
    timeout = 1800
    on-timeout = mmsg dispatch sleep_monitor, eDP-1
    on-resume = mmsg dispatch wakeup_monitor, eDP-1
}
