# Application bindings
bind=SUPER,Return,spawn,foot
bind=SUPER,e,spawn,uwsm-app -- nautilus --new-window
bind=SUPER,b,spawn,google-chrome-stable
bind=SUPER+SHIFT,t,spawn,foot -e btop
bind=SUPER,d,spawn,foot -e lazydocker
bind=SUPER,grave,spawn,Telegram
bind=SUPER,q,spawn,throne
bind=SUPER,l,spawn,localsend

# Menus
bind=SUPER,space,spawn,rofi -show drun

# Control panels
bind=SUPER+SHIFT,a,spawn,foot -e wiremix
bind=SUPER+SHIFT,b,spawn,foot -e bluetui
bind=SUPER+SHIFT,w,spawn,foot -e impala
