# Application bindings
bind=SUPER,Return,spawn,alacritty
bind=SUPER,e,spawn,uwsm-app -- nautilus --new-window
bind=SUPER,b,spawn,google-chrome-stable
bind=SUPER+SHIFT,t,spawn,alacritty -e btop
bind=SUPER,d,spawn,alacritty -e lazydocker
bind=SUPER,grave,spawn,telegram-desktop
bind=SUPER,q,spawn,throne
bind=SUPER,l,spawn,localsend

# Menus
bind=SUPER,space,spawn,rofi -show drun

# Control panels
bind=SUPER+SHIFT,a,spawn,alacritty -e wiremix
bind=SUPER+SHIFT,b,spawn,alacritty -e bluetui
bind=SUPER+SHIFT,w,spawn,alacritty -e impala
