# Laptop multimedia keys for volume and LCD brightness (with OSD)
bindl=NONE,XF86AudioRaiseVolume,spawn,swayosd-client --output-volume raise
bindl=NONE,XF86AudioLowerVolume,spawn,swayosd-client --output-volume lower
bindl=NONE,XF86AudioMute,spawn,swayosd-client --output-volume mute-toggle
bindl=NONE,XF86AudioMicMute,spawn,swayosd-client --input-volume mute-toggle
bindl=NONE,XF86MonBrightnessUp,spawn,swayosd-client --brightness raise
bindl=NONE,XF86MonBrightnessDown,spawn,swayosd-client --brightness lower

# Precise 1% multimedia adjustments with Alt modifier
bindl=ALT,XF86AudioRaiseVolume,spawn,swayosd-client --output-volume +1
bindl=ALT,XF86AudioLowerVolume,spawn,swayosd-client --output-volume -1
bindl=ALT,XF86MonBrightnessUp,spawn,swayosd-client --brightness +1
bindl=ALT,XF86MonBrightnessDown,spawn,swayosd-client --brightness lower -1

# Requires playerctl
bindl=NONE,XF86AudioNext,spawn,swayosd-client --playerctl next
bindl=NONE,XF86AudioPause,spawn,swayosd-client --playerctl play-pause
bindl=NONE,XF86AudioPlay,spawn,swayosd-client --playerctl play-pause
bindl=NONE,XF86AudioPrev,spawn,swayosd-client --playerctl previous

# Switch audio output with $mainMod + Mute
bindl=SUPER,XF86AudioMute,spawn,system-audio-switch

# Screenshot
bind=NONE,Print,spawn,screenshot area
bind=SHIFT,Print,spawn,screenshot

