# Base
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/base_input.conf
source = ~/.config/hypr/conf/visual.conf
source = ~/.config/hypr/conf/rules.conf
source = ~/.config/hypr/conf/misc.conf

# Bindings
source = ~/.config/hypr/bindings/apps.conf
source = ~/.config/hypr/bindings/media.conf
source = ~/.config/hypr/bindings/system.conf
source = ~/.config/hypr/bindings/window_mgmt.conf

# Optionals
source = ~/.config/hypr/hardware.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
