general {
    lock_cmd = hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = mmsg setoption disable_monitor,0 
    inhibit_sleep = 3
}

listener {
    timeout = 1790
    on-timeout = loginctl lock-session
}

listener {
    timeout = 1800
    on-timeout = mmsg setoption disable_monitor,1
    on-resume = mmsg setoption disable_monitor,0 && brightnessctl -r
}
